src/AndresGotta/Bundle/GolfBundle/Entity/Hole.php
<?php

namespace AndresGotta\Bundle\GolfBundle\Entity;

use AndresGotta\Bundle\GolfBundle\ValueObject\Result;
use AndresGotta\Bundle\GolfBundle\ValueObject\StrikeType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * Hole
 *
 * @ORM\Table(name="holes")
 * @ORM\Entity(repositoryClass="AndresGotta\Bundle\GolfBundle\Repository\HoleRepository")
 * @Assert\Callback(methods={"isValidHole"})
 * @UniqueEntity(fields={"number", "round"}, errorPath="number")
 */
class Hole extends AbstractHole
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var DefaultHole
     * @ORM\ManyToOne(targetEntity="AndresGotta\Bundle\GolfBundle\Entity\DefaultHole", inversedBy="holes")
     */
    protected $defaultHole;

    /**
     *
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="AndresGotta\Bundle\GolfBundle\Entity\Strike", mappedBy="hole", cascade={"all"}, orphanRemoval=true)
     * @Assert\Valid()
     * @Assert\Count(min = "1")
     */
    protected $strikes;

    /**
     * @var integer
     *
     * @ORM\Column(name="penality_shots_count", type="integer")
     * @Assert\NotBlank()
     * @Assert\Range(min = 0, max = 12)
     */
    private $penalityShotsCount;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     *
     * @var Round
     * @ORM\ManyToOne(targetEntity="Round", inversedBy="holes", cascade={"persist"}, fetch="LAZY")
     * @ORM\JoinColumn(name="round_id", referencedColumnName="id")
     * @Assert\NotBlank()
     */
    private $round;


    /**
     * Hole constructor.
     */
    public function __construct()
    {
        $this->strikes = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set penalityShotsCount
     *
     * @param integer $penalityShotsCount
     * @return Hole
     */
    public function setPenalityShotsCount($penalityShotsCount)
    {
        $this->penalityShotsCount = $penalityShotsCount;

        return $this;
    }

    /**
     * Get penalityShotsCount
     *
     * @return integer
     */
    public function getPenalityShotsCount()
    {
        return $this->penalityShotsCount;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Hole
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set round
     *
     * @param Round $round
     * @return Hole
     */
    public function setRound(Round $round = null)
    {
        $this->round = $round;

        return $this;
    }

    /**
     * Get round
     *
     * @return Round
     */
    public function getRound()
    {
        return $this->round;
    }
    
    /**
     * Determina si el hoyo fue embocado
     *
     * @return boolean
     */
    public function isHoleOut()
    {
        return $this->strikes->last()->getResult() === Result::HOLE_OUT;
    }

    /**
     * @return int
     */
    public function getTotalStrikes()
    {
        return $this->strikes->count();
    }

    /**
     * @return int
     */
    public function getScore()
    {
        return $this->getTotalStrikes() - $this->penalityShotsCount;
    }

    /**
     * @return int
     */
    public function getTotalPutts()
    {
        return $this->strikes->filter(function (Strike $strike) {
            return $strike->getType() === StrikeType::TYPE_PUTT;
        })->count();
    }

    /**
     *
     */
    public function clearStrikes()
    {
        $this->strikes = new ArrayCollection();
    }

    /**
     * @return Strike[]|Collection
     */
    public function getStrikes()
    {
        return $this->strikes;
    }

    /**
     * @param Strike $strike
     */
    public function addStrike(Strike $strike)
    {
        $strike->setHole($this);
        $this->strikes->add($strike);
    }

    /**
     * @param Strike $strike
     */
    public function removeStrike(Strike $strike)
    {
        $strike->setHole(null);
        $this->strikes->removeElement($strike);
    }

    /**
     * @param $sort
     * @return mixed
     */
    public function getStrikeBySort($sort)
    {
        return $this->strikes[$sort-1];
    }

    /**
     * @return DefaultHole
     */
    public function getDefaultHole()
    {
        return $this->defaultHole;
    }

    /**
     * @param DefaultHole $defaultHole
     */
    public function setDefaultHole($defaultHole)
    {
        $this->defaultHole = $defaultHole;
    }

    /**
     * @param ExecutionContextInterface $context
     */
    public function isValidHole(ExecutionContextInterface $context)
    {
        if ($this->strikes->isEmpty()) {
            return;
        }

        if ($this->strikes->first()->getType() !== StrikeType::TYPE_FIRST) {
            $context->buildViolation('Invalid hole: First strike must be type {1}.', [
                '{1}' => StrikeType::TYPE_FIRST,
            ])->atPath('strikes')->addViolation();
            return;
        }

        $puttDetected = false;
        /* @var Strike $strike */
        foreach ($this->strikes->slice(1) as $strike) {
            if ($strike->getType() === StrikeType::TYPE_FIRST) {
                $context->buildViolation('Invalid hole: Second first strike detected.')
                    ->atPath('strikes')->addViolation();
                return;
            }
            if ($strike->getType() === StrikeType::TYPE_PUTT) {
                $puttDetected = true;
            }
            if ($strike->getType() === StrikeType::TYPE_OTHER && $puttDetected) {
                $context->buildViolation('Invalid hole: Other strike after putt strike detected.')
                    ->atPath('strikes')->addViolation();
                return;
            }
        }

        if ($this->strikes->last()->getResult() !== Result::HOLE_OUT) {
            $context->buildViolation('Invalid hole: Last strike must be hole out.')
                ->atPath('strikes')->addViolation();
            return;
        }

        if ($this->strikes->last()->getReason()) {
            $context->buildViolation('Invalid hole: Last strike has fail reason, must be empty.')
                ->atPath('strikes')->addViolation();
            return;
        }
    }

    /**
     * @param string $type
     * @return Strike[]|Collection
     */
    public function getStrikesByType($type)
    {
        return $this->strikes->filter(function (Strike $strike) use ($type) {
            return $strike->getType() === $type;
        });
    }
}

src/AndresGotta/Bundle/GolfBundle/Controller/Api/DataEntryController.php
<?php

namespace AndresGotta\Bundle\GolfBundle\Controller\Api;

use AndresGotta\Bundle\GolfBundle\Comparative\ChartGroup;
use AndresGotta\Bundle\GolfBundle\CQRS\Command\DeleteHoleCommand;
use AndresGotta\Bundle\GolfBundle\CQRS\Command\DeleteRoundCommand;
use AndresGotta\Bundle\GolfBundle\CQRS\Query\GetDefaultFieldsQuery;
use AndresGotta\Bundle\GolfBundle\CQRS\Query\GetDefaultHolesQuery;
use AndresGotta\Bundle\GolfBundle\CQRS\Query\GetUserComparativeStatsQuery;
use AndresGotta\Bundle\GolfBundle\CQRS\Query\GetUserRoundsQuery;
use AndresGotta\Bundle\GolfBundle\Entity\DefaultField;
use AndresGotta\Bundle\GolfBundle\Entity\DefaultHole;
use AndresGotta\Bundle\GolfBundle\Entity\Hole;
use AndresGotta\Bundle\GolfBundle\Entity\Player;
use AndresGotta\Bundle\GolfBundle\Entity\Round;
use AndresGotta\Bundle\GolfBundle\Event\GolfEvents;
use AndresGotta\Bundle\GolfBundle\Event\RoundEvent;
use AndresGotta\Bundle\GolfBundle\Form\Api\DefaultFieldType;
use AndresGotta\Bundle\GolfBundle\Form\Api\DefaultHoleType;
use AndresGotta\Bundle\GolfBundle\Form\Api\HoleType;
use AndresGotta\Bundle\GolfBundle\Form\Api\PostCompetitiveQuestionnaireType;
use AndresGotta\Bundle\GolfBundle\Form\Api\PreCompetitiveQuestionnaireType;
use AndresGotta\Bundle\GolfBundle\Form\Api\ProfileType;
use AndresGotta\Bundle\GolfBundle\Form\Api\RoundType;
use AndresGotta\Bundle\GolfBundle\ValueObject\Club;
use AndresGotta\Bundle\GolfBundle\ValueObject\Country;
use AndresGotta\Bundle\GolfBundle\ValueObject\Email;
use AndresGotta\Bundle\GolfBundle\ValueObject\FullName;
use AndresGotta\Bundle\GolfBundle\ValueObject\Handicap;
use AndresGotta\Bundle\GolfBundle\ValueObject\PlayerCondition;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\Controller\FOSRestController;
use Nelmio\ApiDocBundle\Annotation\ApiDoc;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\HttpKernelInterface;
use WebFactory\Bundle\UserBundle\Entity\User;

/**
 * Class DataEntryController
 * @Security("is_granted('GPSTATS_ACCESS', user)")
 */
class DataEntryController extends FOSRestController
{
    /**
     * Permite recuperar las vueltas del usuario logueado
     *
     * @ApiDoc(
     *  section="player",
     *  resource=true,
     *  https=true,
     *  tags={"round"},
     *  description="",
     *  output= {
     *      "class"="array<AndresGotta\Bundle\GolfBundle\Entity\Round>",
     *      "groups" = {"my_rounds"},
     *      "parsers"={
     *          "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
     *      }
     *  },
     * )
     *
     * @Rest\View(serializerGroups={"my_rounds"}, serializerEnableMaxDepthChecks=true)
     * @Rest\QueryParam(name="incomplete", description="Incomplete round", strict=true, nullable=true, requirements="true|false")
     * @Rest\QueryParam(name="limit", description="Limit", default="20", requirements="\d+")
     * @Rest\QueryParam(name="offset", description="Offset", default="0", requirements="\d+")
     * @Rest\Get("/rounds")
     * @param string $incomplete
     * @param int $limit
     * @param int $offset
     * @return Round[]
     */
    public function getUserRoundsAction($incomplete = null, $limit = 20, $offset = 0)
    {
        /* @var User $user */
        $user = $this->getUser();
        $query = new GetUserRoundsQuery($user, $incomplete, $limit, $offset);
        $rounds = $this->get('tactician.commandbus')->handle($query);

        return $rounds;
    }

    /**
     * Permite recuperar el detalle de una vuelta del usuario logueado
     *
     * @ApiDoc(
     *  section="player",
     *  resource=true,
     *  https=true,
     *  tags={"round"},
     *  description="",
     *  output= {
     *      "class"="AndresGotta\Bundle\GolfBundle\Entity\Round",
     *      "groups" = {"get_round"},
     *      "parsers"={
     *          "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
     *      }
     *  },
     * )
     *
     * @Rest\View(serializerGroups={"get_round"}, serializerEnableMaxDepthChecks=true)
     * @Rest\Get("/round/{round}")
     * @Security("user == round.getPlayer()")
     * @param Round $round
     * @return Round
     */
    public function getRoundAction(Round $round)
    {
        return $round;
    }

    /**
     * Permite guardar/actualizar el cuestionario pre competitivo de una vuelta
     *
     * @ApiDoc(
     *  section="player",
     *  resource=true,
     *  https=true,
     *  tags={"round"},
     *  description="",
     *  input= {
     *      "class"="AndresGotta\Bundle\GolfBundle\Form\Api\PreCompetitiveQuestionnaireType"
     *  },
     *  output= {
     *      "class"="AndresGotta\Bundle\GolfBundle\Entity\PreCompetitiveQuestionnaire",
     *      "groups" = {"get_round"},
     *      "parsers"={
     *          "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
     *      }
     *  },
     * )
     *
     * @Rest\View(serializerGroups={"get_round"}, serializerEnableMaxDepthChecks=true)
     * @Rest\Put("/round/pre-competitive-questionnaire/save/{round}", name="pre-competitive-questionnaire-save-put")
     * @Rest\Patch("/round/pre-competitive-questionnaire/save/{round}", name="pre-competitive-questionnaire-save-patch")
     * @Security("user == round.getPlayer()")
     * @param Request $request
     * @param Round $round
     * @return Round|array
     */
    public function savePreCompetitiveQuestionnaireAction(Request $request, Round $round)
    {
        $questionnaire = $round->getPreCompetitiveQuestionnaire();
        $form = $this->createForm(new PreCompetitiveQuestionnaireType(), $questionnaire, [
            'method' => $request->getMethod(),
            'csrf_protection' => false,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->get('round_persister')->save($round);

            return $round;
        }

        return ['form' => $form,];
    }

    /**
     * Permite guardar/actualizar el cuestionario post competitivo de una vuelta
     *
     * @ApiDoc(
     *  section="player",
     *  resource=true,
     *  https=true,
     *  tags={"round"},
     *  description="",
     *  input= {
     *      "class"="AndresGotta\Bundle\GolfBundle\Form\Api\PostCompetitiveQuestionnaireType"
     *  },
     *  output= {
     *      "class"="AndresGotta\Bundle\GolfBundle\Entity\PostCompetitiveQuestionnaire",
     *      "groups" = {"get_round"},
     *      "parsers"={
     *          "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
     *      }
     *  },
     * )
     *
     * @Rest\View(serializerGroups={"get_round"}, serializerEnableMaxDepthChecks=true)
     * @Rest\Put("/round/post-competitive-questionnaire/save/{round}", name="post-competitive-questionnaire-save-put")
     * @Rest\Patch("/round/post-competitive-questionnaire/save/{round}", name="post-competitive-questionnaire-save-patch")
     * @Security("user == round.getPlayer()")
     */
    public function savePostCompetitiveQuestionnaireAction(Request $request, Round $round)
    {
        $questionnaire = $round->getPostCompetitiveQuestionnaire();
        $form = $this->createForm(new PostCompetitiveQuestionnaireType(), $questionnaire, [
            'method' => $request->getMethod(),
            'csrf_protection' => false,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->get('round_persister')->save($round);

            return $round;
        }

        return ['form' => $form,];
    }

    /**
     * Permite guardar una vuelta sin el detalle de sus hoyos
     *
     * @ApiDoc(
     *  section="player",
     *  resource=true,
     *  https=true,
     *  tags={"round"},
     *  description="",
     *  input= {
     *      "class"="AndresGotta\Bundle\GolfBundle\Form\Api\RoundType"
     *  },
     *  output= {
     *      "class"="AndresGotta\Bundle\GolfBundle\Entity\Round",
     *      "groups" = {"get_round"},
     *      "parsers"={
     *          "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
     *      }
     *  },
     * )
     *
     * @Rest\View(serializerGroups={"get_round"}, serializerEnableMaxDepthChecks=true)
     * @Rest\Post("/round/save")
     * @Rest\Put("/round/save/{round}", name="saveRoundWithoutHolesActionPut")
     * @Rest\Patch("/round/save/{round}", name="saveRoundWithoutHolesActionPatch")
     * @Security("!round || user == round.getPlayer()")
     */
    public function saveRoundWithoutHolesAction(Request $request, Round $round = null)
    {
        $round = $round ? $round : new Round($this->getUser());
        $form = $this->createForm(new RoundType(), $round, [
            'method' => $request->getMethod(),
            'csrf_protection' => false,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->get('round_persister')->save($round);

            $this->dispatchUpdateScoreEvent($round);

            return $round;
        }

        return ['form' => $form,];
    }

    /**
     * Permite eliminar una vuelta completa
     *
     * @ApiDoc(
     *  section="player",
     *  resource=true,
     *  https=true,
     *  tags={"round"},
     *  description="",
     * )
     *
     * @Rest\View(serializerGroups={"get_round"}, serializerEnableMaxDepthChecks=true)
     * @Rest\Delete("/round/delete/{round}")
     * @Security("user == round.getPlayer()")
     */
    public function deleteRoundAction(Round $round)
    {
        $command = new DeleteRoundCommand($round->getId());
        $this->get('tactician.commandbus')->handle($command);

        $this->dispatchUpdateScoreEvent($round);

        return [];
    }

    /**
     * Permite recuperar las vueltas del usuario logueado
     *
     * @ApiDoc(
     *  section="player",
     *  resource=true,
     *  https=true,
     *  tags={"round"},
     *  description="",
     *  output= {

src/AndresGotta/Bundle/GolfBundle/Resources/views/Frontend/DataEntry/_detail.html.twig
<h2 class="titlewithborderbottomwhite">
    {{ 'Round'|trans }}
    <a role="button" data-toggle="collapse" data-parent="#details" href="#details" aria-expanded="true"
       aria-controls="details"
       class="btn btn-primary" style="float: none;max-width: 200px;margin-left: 65px;margin-top: -35px;">
        {{ 'Detail of round'|trans }}
    </a>
</h2>
<div class="panel-collapse collapse" id="details">
    <a href="{{ path('frontend_round_edit', {'id': round.id}) }}" class="btn btn-primary">{{ 'Edit'|trans }}</a>
    <table class="table table-responsive table-hovered">
        <tr>
            <th>{{ 'Performed at'|trans }}</th>
            <td>{{ round.performedAt|date('d/m/Y') }}</td>
        </tr>
        <tr>
            <th>{{ 'Player Condition'|trans }}</th>
            <td>{{ round.playerCondition|trans }}</td>
        </tr>

        <tr>
            {% if round.playerCondition == constant('AndresGotta\\Bundle\\GolfBundle\\ValueObject\\PlayerCondition::AMATEUR') %}
                <th>{{ 'Handicap'|trans }}</th>
                <td>{{ round.handicap|replace({'-':'+'}) }}</td>
            {% else %}
                <th>{{ 'Tour'|trans }}</th>
                <td>{{ round.tour }}</td>
            {% endif %}
        </tr>

        <tr>
            <th>{{ 'Round Type'|trans }}</th>
            <td>{{ round.roundType|trans }}</td>
        </tr>

        {% if round.roundType == constant('AndresGotta\\Bundle\\GolfBundle\\ValueObject\\RoundType::TOURNAMENT') %}
            <tr>
                <th>{{ 'Tournament Type'|trans }}</th>
                <td>{{ round.detailTournamentType|trans }}</td>
            </tr>
            <tr>
                <th>{{ 'Round Number'|trans }}</th>
                <td>{{ round.roundNumber }}</td>
            </tr>
        {% endif %}
        <tr>
            <th>{{ 'Game Condition'|trans }}</th>
            <td>{{ round.gameCondition|trans }}</td>
        </tr>
        <tr>
            <th>{{ 'Field Type'|trans }}</th>
            <td>{{ round.fieldType|trans }}</td>
        </tr>
        <tr>
            <th>{{ 'Field Par'|trans }}</th>
            <td>{{ round.fieldPar|trans }}</td>
        </tr>
        <tr>
            <th>{{ 'Hole Count'|trans }}</th>
            <td>{{ round.holeCount }}</td>
        </tr>
        <tr>
            <th>{{ 'Strikecount'|trans }}</th>
            <td>{{ round.strikesCount }}</td>
        </tr>
    </table>
</div>

<h2 class="titlewithborderbottomwhite">{{ 'Holes'|trans }}</h2>

{% if round.holeCount != round.holes.count %}
    <div class="alert warning">
        <p>
            {{ 'holes_count'|trans|replace({'%holes%': round.holes.count, '%hole_count%': round.holeCount}) }}
            {{ '(' ~ 'holes_lack'|trans|replace({'%lack%': round.holeCount - round.holes.count}) ~ ')' }}
    </div>

    {% for number in round.remainingHoles if round.holes.count > 0 %}
        <a class="btn btn-primary" href="{{ path('frontend_hole_new', {id:round.id, _number: number}) }}">
            {% trans with {'%number%': number} %}Load hole number %number%{% endtrans %}
        </a>
    {% endfor %}

    {% if round.getNextHoleNumber <= round.holeCount %}
        <a class="btn btn-primary"
           href="{{ path('frontend_hole_new', {id:round.id}) }}">{{ 'Load data of played hole'|trans }}</a></p>
    {% endif %}
{% endif %}


<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true" style="display: inline-block ">
    {% for hole in round.holes %}

        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <div style="position: relative;">
                        <a class="btn-hoyos" role="button" data-toggle="collapse" data-parent="#accordion"
                           href="#collapse{{ loop.index }}" aria-expanded="true"
                           aria-controls="collapse{{ loop.index }}">
                            {{ 'Hole'|trans }} #{{ hole.number }}
                        </a>
                        <div class="extra-data-hoyo">
                            <small style="padding-left: 20px">{{ 'Strikecount' | trans }}:</small>
                            <span>{{ hole.totalStrikes }}</span>
                        </div>
                        <div class="btn-acciones-hoyos">
                            <a class="delete btnOpenDialog"
                               href="{{ path('frontend_hole_delete', {'id': hole.id}) }}">{{ 'Delete'|trans }}</a>
                        </div>
                    </div>
                </h4>
            </div>
            <div id="collapse{{ loop.index }}" class="panel-collapse collapse" role="tabpanel"
                 aria-labelledby="headingOne">
                <div class="panel-body">
                    {% include 'AndresGottaGolfBundle:Frontend/DataEntry:_hole_detail.html.twig' %}
                </div>
            </div>
        </div>


    {% endfor %}
</div>

src/AndresGotta/Bundle/GolfBundle/Resources/views/Frontend/DataEntry/_hole_detail.html.twig
{% set totalStrikes = 1 %}

    <dl class="divider">
        {% if hole.number %}
            <dt>{{ 'Number'|trans }}</dt>
            <dd>{{ hole.number }}</dd>
        {% endif %}

        <dt>{{ 'Par'|trans }}</dt>
        <dd>{{ hole.par }}</dd>

        <dt>{{ 'Total strikes in hole'|trans }}</dt>
        <dd>{{ hole.totalStrikes }}</dd>

        <dt>{{ 'Design'|trans }}</dt>
        <dd>{{ hole.design|trans }}</dd>

        <dt>{{ 'First Strike'|trans }}</dt>
        {% if hole.par == 3 %}
            <dd>{% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_ball_flight_strike_detail.html.twig' with {strike:hole.firstStrike} %}</dd>
        {% else %}
            <dd>{% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_club_ball_flight_strike_detail.html.twig' with {strike:hole.firstStrike} %}</dd>
        {% endif %}


        {% if hole.firstStrikeApproachs.count %}
            <dt>{{ 'First Strike Approachs'|trans }}</dt>
            <dd>
                {% for strike in hole.firstStrikeApproachs %}
                    {% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_strike_lie_and_ball_flight_strike_detail.html.twig' %}
                {% endfor %}
            </dd>
        {% endif %}

        {% if hole.par != 3 and hole.secondStrike %}
            <dt>{{ 'Second Strike'|trans }}</dt>
            {% if hole.par == 5 %}
                <dd>{% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_club_strike_lie_and_ball_flight_strike_detail.html.twig' with {strike:hole.secondStrike} %}</dd>
            {% else %}
                <dd>{% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_strike_lie_and_ball_flight_strike_detail.html.twig' with {strike:hole.secondStrike} %}</dd>
            {% endif %}

            {% if hole.secondStrikeApproachs.count %}
                <dt>{{ 'Second Strike Approachs'|trans }}</dt>
                <dd>
                    {% for strike in hole.secondStrikeApproachs %}
                        {% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_strike_lie_and_ball_flight_strike_detail.html.twig' %}
                    {% endfor %}
                </dd>
            {% endif %}
        {% endif %}

        {% if hole.par == 5 and hole.thirdStrike %}
            <dt>{{ 'Third Strike'|trans }}</dt>
            <dd>{% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_strike_lie_and_ball_flight_strike_detail.html.twig' with {strike:hole.thirdStrike} %}</dd>
            {% if hole.thirdStrikeApproachs.count %}
                {% set totalStrikes = totalStrikes + hole.thirdStrikeApproachs.count %}
                <dt>{{ 'Third Strike Approachs'|trans }}</dt>
                <dd>
                    {% for strike in hole.thirdStrikeApproachs %}
                        {% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_strike_lie_and_ball_flight_strike_detail.html.twig' %}
                    {% endfor %}
                </dd>
            {% endif %}
        {% endif %}

        {% if hole.putt %}
            <dt>{{ 'Putt'|trans }}</dt>
            <dd>{% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_putt_strike_detail.html.twig' with {strike:hole.putt} %}</dd>
            {% if hole.puttApproachs.count %}
                {% set totalStrikes = totalStrikes + hole.puttApproachs.count %}
                <dt>{{ 'Putt Approachs'|trans }}</dt>
                <dd>
                    {% for strike in hole.puttApproachs %}
                        {% include 'AndresGottaGolfBundle:Frontend/DataEntry:strike/_putt_strike_detail.html.twig' %}
                    {% endfor %}
                </dd>
            {% endif %}
        {% endif %}

        <dt>{{ 'Penality shots'|trans }}</dt>
        <dd>{{ hole.penalityShotsCount }}</dd>

        <dt>{{ 'Description'|trans }}</dt>
        {% if hole.description %}
            <dd>{{ hole.description }}</dd>
        {% else %}
            <dd>{{ 'no description'|trans }}</dd>
        {% endif %}
    </dl>

<script>
    $('.details').on('click', function(e) {
        e.preventDefault();
        $('.details-table').toggle('slow');
    })
</script>