src/AndresGotta/Bundle/GolfBundle/Entity/Category.php
<?php

namespace AndresGotta\Bundle\GolfBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Inflector\Inflector;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use APY\DataGridBundle\Grid\Mapping as Grid;

/**
 * @ORM\Table(name="report_categories")
 * @ORM\Entity(repositoryClass="AndresGotta\Bundle\GolfBundle\Repository\CategoryRepository")
 * @Grid\Source(columns="id, name, parent.name, description, groups.id:count", groupBy={"id"})
 */
class Category
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Grid\Column(visible=false, filterable=false)
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Grid\Column(title="Name")
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     * @Grid\Column(title="Description")
     */
    private $description;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AndresGotta\Bundle\GolfBundle\Entity\GroupReport", mappedBy="category", cascade={"all"})
     * @Grid\Column(title="Groups", field="reportCategories.id:count", filterable=false)
     */
    private $groups;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="AndresGotta\Bundle\GolfBundle\Entity\Category", inversedBy="children", cascade={"persist"})
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     * @Grid\Column(title="Parent", field="parent.name", filter="select", selectFrom="source", operators={"like"})
     */
    private $parent;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AndresGotta\Bundle\GolfBundle\Entity\Category", mappedBy="parent", cascade={"persist"})
     */
    private $children;

    /**
     * 
     */
    public function __construct()
    {
        $this->children = new ArrayCollection();
        $this->reports = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->name;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * 
     * @param string $name
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;
        
        return $this;
    }

    /**
     * 
     * @param string $description
     * @return Category
     */
    public function setDescription($description)
    {
        $this->description = $description;
        
        return $this;
    }

    /**
     * @return Category
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @param $parent
     * @return Category
     */
    public function setParent($parent = null)
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @param null $par
     * @return bool
     */
    public function haveReportPar($par = null)
    {
        foreach ($this->reports as $report) {
            if ($report->getPar() === $par) {
                return true;
            }
        }
        
        foreach ($this->children as $child) {
            if ($child->haveReportPar($par)) {
                return true;
            }
        }
    }

    /**
     * Add child
     *
     * @param Category $child
     *
     * @return Category
     */
    public function addChild(Category $child)
    {
        $child->setParent($this);
        $this->children[] = $child;

        return $this;
    }

    /**
     * Remove child
     *
     * @param Category $child
     */
    public function removeChild(Category $child)
    {
        $child->setParent();
        $this->children->removeElement($child);
    }

    /**
     * @return ArrayCollection
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Add group
     *
     * @param GroupReport $group
     *
     * @return Category
     */
    public function addGroup(GroupReport $group)
    {
        $this->groups[] = $group;

        return $this;
    }

    /**
     * Remove group
     *
     * @param GroupReport $group
     */
    public function removeGroup(GroupReport $group)
    {
        $this->groups->removeElement($group);
    }

    /**
     * Get groups
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * @return string
     */
    public function getSlug()
    {
        $name = str_replace(' - ', '', $this->name);
        $name = str_replace(',', ' ', $name);
        $name = str_replace('/', '', $name);

        return $this->id . strtolower(str_replace(' ', '-', Inflector::classify($name)));
    }

    /**
     * @return array
     */
    public function getChildrenSlug()
    {
        $slugs = [];
        foreach ($this->children as $child) {
            $slugs[] = '.' . $child->getSlug();
        }

        return implode(' ', array_unique($slugs));
    }
}

src/AndresGotta/Bundle/GolfBundle/Form/ReportType.php
<?php

namespace AndresGotta\Bundle\GolfBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class ReportType
 * @package AndresGotta\Bundle\GolfBundle\Form
 */
class ReportType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reportCode')
            ->add('par', 'choice', ['choices' => ['', '3', '4', '5']])
            ->add('objectives', 'ckeditor', [
                'config_name' => 'default'
            ])
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'AndresGotta\Bundle\GolfBundle\Entity\Report',
            'attr' => ['novalidate' => 'novalidate']
        ]);
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'report_type';
    }

}

src/AndresGotta/Bundle/GolfBundle/Controller/Backend/CategoryController.php
<?php

namespace AndresGotta\Bundle\GolfBundle\Controller\Backend;

use AndresGotta\Bundle\GolfBundle\Entity\Category;
use AndresGotta\Bundle\GolfBundle\Form\CategoryType;
use APY\DataGridBundle\Grid\Action\MassAction;
use APY\DataGridBundle\Grid\Action\RowAction;
use APY\DataGridBundle\Grid\Row;
use APY\DataGridBundle\Grid\Source\Entity;
use Doctrine\ORM\QueryBuilder;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/golf/reports/category")
 */
class CategoryController extends Controller
{
    /**
     * @Route("/", name="backend_report_categorys")
     * @Method("GET|POST")
     * @Template
     */
    public function indexAction()
    {
        /* @var $source \APY\DataGridBundle\Grid\Source\Entity */
        $source = new Entity('AndresGottaGolfBundle:Category');

        /* @var $grid \APY\DataGridBundle\Grid\Grid */
        $grid = $this->get('grid');

        $source->manipulateRow(function  (Row $row) {
            $category = $row->getEntity();
            if ($category->getParent()) {
                $row->setClass($category->getParent()->getSlug());
                $row->setColor('#f1f1f1');
            } else {
                $row->setClass($category->getSlug());
            }

            return $row;
        });

        $grid->setSource($source);

        $showRowAction = new RowAction('Edit', 'backend_report_category_edit', false, '_self', array('class' => 'btn-action glyphicons pencil btn-success'));
        $grid->addRowAction($showRowAction);
        $deleteRowAction = new RowAction('Delete', 'backend_report_category_delete', true, '_self', array('class' => 'btn-action glyphicons remove_2 btn-danger'));
        $grid->addRowAction($deleteRowAction);

//        $em = $this->getDoctrine()->getManager();
//        $services = $em->getRepository('AndresGottaServiceBundle:Service')->findAll();
//
//        foreach ($services as $service) {
//            $action = new MassAction($this->get('translator')->trans('Add service %name%', ['%name%' => $service->getName()]), function($primaryKeys) use ($em, $service) {
//                foreach ($primaryKeys as $key) {
//                    $report = $em->getRepository('AndresGottaGolfBundle:Report')->find($key);
//                    if ($report) {
//                        $report->addServicesNeeded($service);
//                        $em->persist($report);
//                    }
//                }
//
//                $em->flush();
//                $this->addFlash('info', $this->get('translator')->trans('flash.message.generic.updated'));
//            }, true);
//            $grid->addMassAction($action);
//        }
//
//        $action = new MassAction($this->get('translator')->trans('Remove all services'), function ($primaryKeys) use ($em) {
//            foreach ($primaryKeys as $key) {
//                $report = $em->getRepository('AndresGottaGolfBundle:Report')->find($key);
//                $report->removeAllServicesNeeded();
//                $em->persist($report);
//            }
//            $em->flush();
//        });
//        $grid->addMassAction($action);

        return $grid->getGridResponse('AndresGottaGolfBundle:Backend\Category:index.html.twig');
    }

    /**
     * @Route("/crete/category", name="backend_report_category_create")
     * @Template()
     */
    public function createAction(Request $request)
    {
        $reportCategory = new Category();
        $form = $this->createForm(new CategoryType(), $reportCategory, [
            'action' => $this->generateUrl('backend_report_category_create'),
            'method' => 'POST'
        ]);
        $form->add('submit', 'submit', ['label' => 'Guardar', 'attr' => ['class' => 'btn btn-primary']]);

        $form->handleRequest($request);
        if ($form->isValid()) {
            $this->getDoctrine()->getManager()->persist($reportCategory);
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', $this->get('translator')->trans('flash.message.generic.created'));

            return $this->redirectToRoute('backend_report_categorys');
        }

        return ['form' => $form->createView()];
    }


    /**
     * @Route("/{id}/edit", name="backend_report_category_edit")
     * @Template()
     */
    public function editAction(Request $request, Category $reportCategory)
    {
        $form = $this->createForm(new CategoryType(), $reportCategory, [
            'action' => $this->generateUrl('backend_report_category_edit', ['id' => $reportCategory->getId()]),
            'method' => 'PUT'
        ]);
        $form->add('submit', 'submit', ['label' => 'Guardar', 'attr' => ['class' => 'btn btn-primary']]);

        $form->handleRequest($request);
        if ($form->isValid()) {
            foreach ($reportCategory->getReports() as $report) {
                $report->completeSlug();
                $this->getDoctrine()->getManager()->persist($report);
            }

            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', $this->get('translator')->trans('flash.message.generic.updated'));

            return $this->redirectToRoute('backend_report_categorys');
        }

        return ['form' => $form->createView(), 'report' => $reportCategory];
    }

    /**
     * @Route("/{id}/delete", name="backend_report_category_delete")
     */
    public function deleteAction(Category $category)
    {
        if ($category->getChildren()->count() > 0) {
            $this->addFlash('error', $this->get('translator')->trans('flash.message.generic.has_children'));
        } else {
            $this->getDoctrine()->getManager()->remove($category);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', $this->get('translator')->trans('flash.message.generic.delete'));
        }


        return $this->redirectToRoute('backend_report_categorys');
    }

    /**
     * @param Request $request
     * @return JsonResponse
     * @Route("/ajax_call", name="ajax_report_categorys")
     * @Method("GET")
     */
    public function categorySearchAction(Request $request)
    {
        $value = $request->get('term');

        $em = $this->getDoctrine()->getEntityManager();
        $categorys = $em->getRepository('AndresGottaGolfBundle:Category')->createQueryBuilder('t')
            ->where("t.name like :name")->setParameter('name', "%{$value}%")
            ->getQuery()->getResult();

        $json = array();
        foreach ($categorys as $category) {
            $json[] = array(
                'label' => $category->getName(),
                'value' => $category->getName()
            );
        }

        return new JsonResponse($json);
    }

}

src/AndresGotta/Bundle/GolfBundle/Controller/Backend/ComparativeController.php
<?php

namespace AndresGotta\Bundle\GolfBundle\Controller\Backend;

use AndresGotta\Bundle\GolfBundle\Entity\Comparative;
use AndresGotta\Bundle\GolfBundle\Form\ComparativeType;
use APY\DataGridBundle\Grid\Action\MassAction;
use APY\DataGridBundle\Grid\Action\RowAction;
use APY\DataGridBundle\Grid\Source\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class ComparativeController
 * @package AndresGotta\Bundle\GolfBundle\Controller\Frontend
 *
 * @Route("/comparatives")
 */
class ComparativeController extends Controller
{
    /**
     * @Route("/", name="backend_comparative_index")
     */
    public function indexAction()
    {
        /* @var $source \APY\DataGridBundle\Grid\Source\Entity */
        $source = new Entity('AndresGottaGolfBundle:Comparative');

        /* @var $grid \APY\DataGridBundle\Grid\Grid */
        $grid = $this->get('grid');
        $grid->setSource($source);

        $showRowAction = new RowAction('Edit', 'backend_comparative_edit', false, '_self', array('class' => 'btn-action glyphicons pencil btn-success'));
        $grid->addRowAction($showRowAction);

//        $em = $this->getDoctrine()->getManager();
//        $services = $em->getRepository('AndresGottaServiceBundle:Service')->findAll();
//
//        foreach ($services as $service) {
//            $action = new MassAction($this->get('translator')->trans('Add service %name%', ['%name%' => $service->getName()]), function($primaryKeys) use ($em, $service) {
//                foreach ($primaryKeys as $key) {
//                    $report = $em->getRepository('AndresGottaGolfBundle:Comparative')->find($key);
//                    if ($report) {
//                        $report->addServicesNeeded($service);
//                        $em->persist($report);
//                    }
//                }
//
//                $em->flush();
//                $this->addFlash('info', $this->get('translator')->trans('flash.message.generic.updated'));
//            }, true);
//            $grid->addMassAction($action);
//        }
//
//        $action = new MassAction($this->get('translator')->trans('Remove all services'), function ($primaryKeys) use ($em) {
//            foreach ($primaryKeys as $key) {
//                $report = $em->getRepository('AndresGottaGolfBundle:Comparative')->find($key);
//                $report->removeAllServicesNeeded();
//                $em->persist($report);
//            }
//            $em->flush();
//        });
//        $grid->addMassAction($action);

        return $grid->getGridResponse('AndresGottaGolfBundle:Backend\Comparative:index.html.twig', compact('services'));
    }

    /**
     * @Route("/{id}/edit", name="backend_comparative_edit")
     * @Template()
     */
    public function editAction(Request $request, Comparative $comparative)
    {
        $form = $this->createForm(new ComparativeType(), $comparative, [
            'action' => $this->generateUrl('backend_comparative_edit', ['id' => $comparative->getId()]),
            'method' => 'PUT'
        ]);
        $form->add('submit', 'submit', ['label' => 'Guardar', 'attr' => ['class' => 'btn btn-primary']]);

        $form->handleRequest($request);
        if ($form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', $this->get('translator')->trans('flash.message.generic.updated'));

            return $this->redirectToRoute('backend_comparative_index');
        }

        return ['form' => $form->createView(), 'comparative' => $comparative];
    }
}

src/AndresGotta/Bundle/GolfBundle/Resources/views/Backend/Report/edit.html.twig
{% extends '::base.html.twig' %}

{% import '::macros.html.twig' as macros %}

{% block headline %}{{ macros.title('Report edit') }}{% endblock headline %}

{% block content -%}
    {{ form(form) }}
{% endblock %}

{% block head_style %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/andresgottahomepage/css/select2.min.css') }}" />
    {{ form_stylesheet(form) }}
{% endblock %}

{% block foot_script %}
    {{ parent() }}
    <script>
        $('select').select2();
    </script>
    {{ form_javascript(form) }}
{% endblock %}

src/AndresGotta/Bundle/GolfBundle/Resources/views/Backend/Report/grid.html.twig
{% extends '::grid.html.twig' %}

{% block grid_column_name_cell %}
    {% set value = value|trans %}
    {{ block('grid_column_cell') }}
{% endblock grid_column_name_cell %}

{% block grid_column_reportType_name_cell %}
    {% set value = value|trans %}
    {{ block('grid_column_cell') }}
{% endblock grid_column_reportType_name_cell %}

src/AndresGotta/Bundle/GolfBundle/Resources/views/Backend/Report/index.html.twig
{% extends '::base.html.twig' %}

{% import '::macros.html.twig' as macros %}

{% block headline %}{{ macros.title('Report list') }}{% endblock headline %}

{% block content -%}
    {% include '::filters.html.twig' with {'grid':grid, 'gridBlock':'AndresGottaGolfBundle:Backend/Report:grid.html.twig'} only %}
    {{ grid(grid, 'AndresGottaGolfBundle:Backend/Report:grid.html.twig') }}
{% endblock %}

src/AndresGotta/Bundle/GolfBundle/Resources/views/Backend/Report/user.html.twig
{% extends '::base.html.twig' %}

{% import '::macros.html.twig' as macros %}

{% block headline %}{{ macros.title('Report') }}{% endblock headline %}

{% form_theme filter_form _self %}

{%- block choice_widget_options -%}
    {% for group_label, choice in options %}
        {% set attr = choice.attr %}
        <option value="{{ choice.value }}" {{ block('attributes') }}{% if choice is selectedchoice(value) %} selected="selected"{% endif %}>{{ choice.label|trans }}</option>
    {% endfor %}
{%- endblock choice_widget_options -%}

{% block content -%}
<div class="row-fluid">
    <div class="row">
        <div class="span12 reportZone2">
            <div class="span10">
            {{ form(filter_form) }}
                </div>
            </div>
        </div>
        <hr />
        <div id="report" class="row-fluid span10">
        {% if data.columns is defined and data.columns|length == 0 %}
        {{ 'No result'|trans }}
        {% elseif data is not null %}
                <div class="row">
                    <div class="span12 reportZone">
                        <div class="reportZoneContent">
                            <h1 class="reportZoneTitle">{{ report.name|trans }}</h1>
                            {#<p>{{ report.description|trans }}</p>#}
                            <br/>
                            {% if filterForm is defined %}
                            {{ form(filterForm, {'attr':{'novalidate':'novalidate'} }) }} 
                            {% endif %}
                            <div class="reportZoneGraphic row-fluid">
                                <div class="reportZoneGraphicBox">{% include 'AndresGottaGolfBundle:Frontend/Report:reports/' ~ report.slug ~ '.html.twig' %}</div>
                                <p class="reportZoneGraphicDesc">{{ 'Goals'|trans }}: {{ report.objectives|trans }}</p>
                            </div>
                        </div>
                    </div>
                </div>
        {% endif %}
            </div>
        </div>
        <style type="text/css">
                .reportZone .reportZoneContent {
                    background: none repeat scroll 0 0 #F7F7F7;
                    border: 1px solid #C0C0C0;
                    display: block;
                    margin: 0 1%;
                    overflow: hidden;
                    padding: 2%;
                    width: 96%;
                }
                .reportZone2 form fieldset {
                    background: none repeat scroll 0 0 #F7F7F7;
                    border: 1px solid #C0C0C0;
                    margin: 0 4%;
                    padding: 1% 2%;
                    width: 95%;
                }
                .reportZone2 .control-group {
                    display: inline-block;
                    margin-bottom: 10px;
                    margin-right: 2%;
                    vertical-align: top;
                    width: auto;
                }
                .reportZone2 select {
                    display: inline-block;
                    margin-bottom: 10px;
                    margin-right: 2px;
                    vertical-align: top;
                }
                .row .reportZone {
                    background: none repeat scroll 0 0 #FFFFFF;
                    display: block;
                    float: none;
                    margin: 20px auto;
                    overflow: hidden;
                    padding: 0;
                    width: 100%;
                }
                .row .reportZone .reportZoneTitle {
                    border-bottom: 2px solid #CCCCCC;
                    color: #333333;
                    font-size: 21px;
                    font-weight: bold;
                    line-height: 23px;
                    margin: 0 0 15px;
                    padding: 0 0 15px;
                    text-align: center;
                    text-transform: uppercase;
                }
                .row .reportZone h2 {
                    color: #333333;
                    font-size: 16px;
                    font-weight: bold;
                    line-height: 18px;
                    margin: 0 0 10px;
                    padding: 0;
                    text-align: left;
                    text-transform: uppercase;
                }
                .row .reportZone .reportZoneContent {
                    display: block;
                    overflow: hidden;
                    padding: 1.4%;
                }
                .row .reportZone .reportZoneContent p {
                    font-weight: 300;
                }
                .row .reportZone .reportZoneGraphic {
                    display: block;
                    overflow: hidden;
                    width: 100%;
                }
                .row .reportZone .reportZoneGraphicBox {
                    background: none repeat scroll 0 0 #F7F7F7;
                    display: block;
                    margin: 0 0 15px;
                    overflow: hidden;
                    width: 100%;
                }
                .row .reportZone .reportZoneData {
                    background: none repeat scroll 0 0 #F7F7F7;
                    display: block;
                    margin: 0 0 15px;
                    overflow: hidden;
                    width: 100%;
                }
                .row .reportZone .reportZoneGraphic p {
                    color: #666666;
                    font-size: 14px;
                    font-weight: bold;
                    line-height: 16px;
                }
                .row .reportZone .reportZoneGraphic h2 {
                    border-bottom: 2px solid #DDDDDD;
                    padding: 12px;
                }
                .row .reportZone .reportZoneGraphic .table tr th {
                    background: none repeat scroll 0 0 #F9F9F9;
                    border-right: 1px solid #DDDDDD;
                }
                .row .reportZone .reportZoneGraphic .table tr td {
                    border-right: 1px solid #DDDDDD;
                }
                .row .reportZone .reportZoneGraphic caption {
                    background: none repeat scroll 0 0 #DDDDDD;
                    font-weight: bold;
                    padding: 5px 0;
                    text-align: center;
                    text-transform: uppercase;
                }
                .graphicBoxContainer.small {
                    background: none repeat scroll 0 0 #FFFFFF;
                    height: 400px;
                    margin: 0 auto;
                    width: 434px;
                }
                .graphicBoxContainer.long {
                    background: none repeat scroll 0 0 #FFFFFF;
                    height: 400px;
                    margin: 0 auto;
                    width: 680px;
                }
                .reportZoneGraphicBox .table {
                    border: 2px solid #DDDDDD;
                    margin: 20px auto;
                    padding: 0;
                    width: 98%;
                }
                .reportZoneContent .control-group {
                    display: inline-block;
                    margin-bottom: 10px;
                    margin-right: 25px;
                    vertical-align: top;
                }
                .reportZoneContent form fieldset {
                    background: none repeat scroll 0 0 #F7F7F7;
                    border: 1px solid #C0C0C0;
                    margin: 0 2px;
                    padding: 12px;
                }
                .reportZoneContent form fieldset .btn {
                    background: none repeat scroll 0 0 #F68A30;
                    border: medium none;
                    display: block;
                    float: left;
                    font-size: 14px;
                    font-weight: 500;
                    line-height: 20px;
                    margin: 0;
                    padding: 4px 15px;
                    text-transform: uppercase;
                    vertical-align: top;
                }
            </style>
{%- endblock content %}

{% block foot_script %}
{{ parent() }}
            <script type="text/javascript" src="{{ asset('bundles/andresgottafrontendtheme/js/highcharts.js') }}"></script>
{% endblock foot_script %}