src/AndresGotta/Bundle/GroupBundle/Entity/Group.php
<?php

namespace AndresGotta\Bundle\GroupBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use APY\DataGridBundle\Grid\Mapping as Grid;

/**
 * Class Group
 * @package AndresGotta\Bundle\GroupBundle\Entity
 *
 * @ORM\Entity(repositoryClass="AndresGotta\Bundle\GroupBundle\Doctrine\ORM\GroupRepository")
 * @ORM\Table(name="groups")
 * @Grid\Source(columns="id, authorized, createdAt, name, minimumQuantity, players.id:count", groupBy={"id"})
 */
class Group //implements ServiceNeededInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Grid\Column(visible=false, filterable=false)
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank()
     * @Grid\Column(title="Name", filterable=true)
     */
    protected $name;

    /**
     * @var boolean
     *
     * @ORM\Column(name="authorized", type="boolean")
     * @Grid\Column(title="Authorized", filterable=true)
     */
    protected $authorized = false;

    /**
     * @var boolean
     *
     * @ORM\Column(name="enabled", type="boolean")
     */
    protected $enabled = true;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @Grid\Column(title="Created At", filterable=true)
     */
    protected $createdAt;

    /**
     * @var integer
     *
     * @ORM\Column(name="minimum_quantity", type="integer", nullable=true)
     * @Grid\Column(title="Minimum Quantity", filterable=true)
     */
    protected $minimumQuantity;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AndresGotta\Bundle\GroupBundle\Entity\GroupPlayer", mappedBy="group", cascade={"persist"}, orphanRemoval=true)
     * @Assert\Valid()
     * @Grid\Column(title="Players", field="players.id:count", filterable=false)
     */
    protected $players;

//    /**
//     * @ORM\ManyToMany(targetEntity="AndresGotta\Bundle\ServiceBundle\Entity\Service")
//     * @ORM\JoinTable(name="groups_services",
//     *      joinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")},
//     *      inverseJoinColumns={@ORM\JoinColumn(name="service_id", referencedColumnName="id")}
//     *      )
//     */
//    protected $servicesNeeded;

    /**
     * Group constructor.
     */
    public function __construct()
    {
        $this->players = new ArrayCollection();
//        $this->servicesNeeded = new ArrayCollection();
        $this->createdAt = new \DateTime;
        $this->minimumQuantity = 25;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }
    
    /**
     * @return boolean
     */
    public function isAuthorized()
    {
        return $this->authorized;
    }

    /**
     * @param boolean $authorized
     */
    public function setAuthorized($authorized)
    {
        $this->authorized = $authorized;
    }

    /**
     * @return boolean
     */
    public function isEnabled()
    {
        return $this->enabled;
    }

    /**
     * @param boolean $enabled
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return int
     */
    public function getMinimumQuantity()
    {
        return $this->minimumQuantity;
    }

    /**
     * @param int $minimumQuantity
     */
    public function setMinimumQuantity($minimumQuantity)
    {
        $this->minimumQuantity = $minimumQuantity;
    }


    /**
     * Get authorized
     *
     * @return boolean
     */
    public function getAuthorized()
    {
        return $this->authorized;
    }

    /**
     * Get enabled
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Add player
     *
     * @param GroupPlayer $player
     *
     * @return Group
     */
    public function addPlayer(GroupPlayer $player)
    {
        $this->players[] = $player;
        $player->setGroup($this);

        return $this;
    }

    /**
     * Remove player
     *
     * @param GroupPlayer $player
     */
    public function removePlayer(GroupPlayer $player)
    {
        $this->players->removeElement($player);
        $player->setGroup(null);
    }

    /**
     * Get players
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPlayers()
    {
        return $this->players;
    }
//
//    /**
//     * @return ArrayCollection
//     */
//    public function getServicesNeeded()
//    {
//        return $this->servicesNeeded;
//    }
//
//    /**
//     * Add servicesNeeded
//     *
//     * @param Service $servicesNeeded
//     *
//     * @return Group
//     */
//    public function addServicesNeeded(Service $servicesNeeded)
//    {
//        $this->servicesNeeded[] = $servicesNeeded;
//
//        return $this;
//    }
//
//    /**
//     * Remove servicesNeeded
//     *
//     * @param Service $servicesNeeded
//     */
//    public function removeServicesNeeded(Service $servicesNeeded)
//    {
//        $this->servicesNeeded->removeElement($servicesNeeded);
//    }

    /**
     * @return string
     */
    public function getAdmin()
    {
        /** @var GroupPlayer $player */
        foreach ($this->players as $player) {
            if ($player->isAdmin()) {
                return (string) $player->getPlayer()->getProfile();
            }
        }
    }

    /**
     * @return array
     */
    public function getUserAdmins()
    {
        $admins = [];
        foreach ($this->players as $player) {
            if ($player->isAdmin()) {
                $admins[] = $player->getPlayer();
            }
        }

        return $admins;
    }
}

src/AndresGotta/Bundle/GroupBundle/Entity/GroupPlayer.php
<?php

namespace AndresGotta\Bundle\GroupBundle\Entity;

use AndresGotta\Bundle\GroupBundle\ValueObject\PlayerStatuses;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use WebFactory\Bundle\UserBundle\Entity\User;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class GroupPlayer
 * @package AndresGotta\Bundle\GroupBundle\Entity
 *
 * @ORM\Entity()
 * @ORM\Table(name="group_players")
 */
class GroupPlayer
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var Group
     *
     * @ORM\ManyToOne(targetEntity="AndresGotta\Bundle\GroupBundle\Entity\Group", inversedBy="players")
     * @ORM\JoinColumn(name="group_id", referencedColumnName="id")
     */
    protected $group;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="WebFactory\Bundle\UserBundle\Entity\User", inversedBy="playerGroups")
     * @ORM\JoinColumn(name="player_id", referencedColumnName="id")
     * @Assert\NotNull()
     */
    protected $player;

    /**
     * @var boolean
     *
     * @ORM\Column(name="wanna_be_admin", type="boolean")
     */
    protected $wannaBeAdmin;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_admin", type="boolean")
     */
    protected $isAdmin = false;

    /**
     * @var boolean
     *
     * @ORM\Column(name="confirmed", type="boolean")
     */
    protected $confirmed = false;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string", length=64, nullable=true)
     */
    protected $status;

    /**
     * GroupPlayer constructor.
     */
    public function __construct()
    {
        $this->status = PlayerStatuses::PENDING;
        $this->wannaBeAdmin = false;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Group
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * @param Group $group
     * @return GroupPlayer
     */
    public function setGroup(Group $group = null)
    {
        $this->group = $group;

        return $this;
    }

    /**
     * @return User
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * @param UserInterface $player
     * @return $this
     */
    public function setPlayer(UserInterface $player)
    {
        $this->player = $player;

        return $this;
    }

    /**
     * @return boolean
     */
    public function isConfirmed()
    {
        return $this->confirmed;
    }

    /**
     * @param boolean $confirmed
     */
    public function setConfirmed($confirmed)
    {
        $this->confirmed = $confirmed;
    }

    /**
     * @return boolean
     */
    public function isAdmin()
    {
        return $this->isAdmin;
    }

    /**
     * @param boolean $isAdmin
     * @return GroupPlayer|boolean
     * @throws \Exception
     */
    public function setIsAdmin($isAdmin)
    {
        if (!in_array(User::ROLE_GROUP_OWNER, $this->player->getRoles())) {
            throw new \Exception('The player must has a Group Owner role');
        }

        $this->isAdmin = $isAdmin;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getGroupMember()
    {
        if (in_array($this->status, [PlayerStatuses::CONFIRMED, PlayerStatuses::PENDING])) {
            return true;
        }

        return false;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param string $status
     * @return GroupPlayer
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return bool
     */
    public function getWannaBeAdmin()
    {
        return $this->wannaBeAdmin;
    }

    /**
     * @param $wannaBeAdmin
     */
    public function setWannaBeAdmin($wannaBeAdmin)
    {
        $this->wannaBeAdmin = $wannaBeAdmin;
    }

}

src/AndresGotta/Bundle/GroupBundle/Controller/Backend/GroupController.php
<?php

namespace AndresGotta\Bundle\GroupBundle\Controller\Backend;

use AndresGotta\Bundle\GroupBundle\Entity\Group;
use AndresGotta\Bundle\GroupBundle\Entity\GroupPlayer;
use AndresGotta\Bundle\GroupBundle\Form\Type\GroupType;
use APY\DataGridBundle\Grid\Action\RowAction;
use APY\DataGridBundle\Grid\Source\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use WebFactory\Bundle\UserBundle\Entity\User;

/**
 * Class GroupController
 * @package AndresGotta\Bundle\GroupBundle\Controller\Backend
 */
class GroupController extends Controller
{
    /**
     * @Route("/", name="backend_group_index")
     */
    public function indexAction()
    {
        $source = new Entity('AndresGottaGroupBundle:Group');

        $grid = $this->get('grid');
        $grid->setSource($source);

        $editAction = new RowAction('Authorized', 'backend_group_authorized', false, '_self', array('class' => 'btn-action glyphicons settings btn-success'));
        $grid->addRowAction($editAction);

        $deleteAction = new RowAction('Delete', 'backend_group_delete', true, '_self', array('class' => 'btn-action glyphicons remove btn-danger'));
        $grid->addRowAction($deleteAction);

        $groupPlayerRepository = $this->getDoctrine()->getRepository('AndresGottaGroupBundle:GroupPlayer');
        $wannaBeAdmins = $groupPlayerRepository->findBy(['wannaBeAdmin' => true]);

        $adminRequests = [];
        foreach ($wannaBeAdmins as $wannaBeAdmin) {
            $adminRequest['username'] = $wannaBeAdmin->getPlayer()->getUsername();
            $adminRequest['groupName'] = $wannaBeAdmin->getGroup()->getName();
            $adminRequest['groupId'] = $wannaBeAdmin->getGroup()->getId();
            $adminRequest['groupPlayerId'] = $wannaBeAdmin->getId();
            $adminRequests[] = $adminRequest;
        }

        return $grid->getGridResponse('AndresGottaGroupBundle:Backend\Group:index.html.twig', ['adminRequests' => $adminRequests]);
    }

    /**
     * @Route("/group/{id}/authorized", name="backend_group_authorized")
     * @Template("AndresGottaGroupBundle:Backend/Group:edit.html.twig")
     */
    public function authorizedAction(Request $request, Group $group)
    {
        $form = $this->createForm(new GroupType(true), $group, [
            'action' => $this->generateUrl('backend_group_authorized', ['id' => $group->getId()]),
            'method' => 'PUT'
        ]);
        $form->add('Guardar', 'submit');

        if ($request->getMethod() === Request::METHOD_PUT) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $this->getDoctrine()->getManager()->persist($group);
                $this->getDoctrine()->getManager()->flush();

                $this->addFlash('success', $this->get('translator')->trans('flash.message.generic.updated'));

                return $this->redirectToRoute('backend_group_index');
            } else {
                $this->addFlash('danger', 'Datos erroneos');
            }
        }

        return ['form' => $form->createView(), 'group' => $group];
    }

    /**
     * @Route("/group/{id}/delete", name="backend_group_delete")
     */
    public function deleteAction(Group $group)
    {
        try {
            $this->getDoctrine()->getManager()->remove($group);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', $this->get('translator')->trans('flash.message.generic.delete'));
        } catch (\Exception $e) {
            $this->addFlash('danger', $e->getMessage());
        }


        return $this->redirectToRoute('backend_group_index');
    }

    /**
     * @param GroupPlayer $groupPlayer
     * @param boolean $response
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     *
     * @Route("/admin-request/{groupPlayer}/reply/{response}", name="backend_group_reply_admin_request")
     */
    public function replyAdminRequest(GroupPlayer $groupPlayer, $response)
    {
        if ($response === 'true') {
            $groupPlayer->getPlayer()->addRole(User::ROLE_GROUP_OWNER);
            $groupPlayer->setIsAdmin(true);
        }
        $groupPlayer->setWannaBeAdmin(false);

        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('backend_group_index');
    }
}

src/AndresGotta/Bundle/GroupBundle/Resources/views/Frontend/Group/create.html.twig
{% extends '::base.html.twig' %}

{% macro player_prototype(playerField) %}
    <div class="form-group" style="margin-bottom: 8px">
        <div class="row-fluid">
            <div class="span7 offset1">
                {{ form_widget(playerField.player) }}
            </div>
            <div class="span4">
                <a href="#" class="collection-delete btn btn-danger">Quitar</a>
                <a href="#" class="collection-add btn btn-success">Agregar</a>
            </div>
        </div>
        <section class="validation">{{ form_errors(playerField.player) }}</section>
    </div>
{% endmacro %}

{% block content -%}

    <div class="nuevo-dashboard">
        <div class="reportarea">
            {% include '@AndresGottaHomepage/Frontend/Homepage/dashboard_sidebar.html.twig' %}

            <div class="bloque-central-stats">
                {{ form_start(form) }}
                    {{ form_row(form.name) }}
                    <div id="player-list" data-prototype="{{ _self.player_prototype(form.players.vars.prototype)|e }}">
                        {% for playerField in form.players %}
                            {{ _self.player_prototype(playerField) }}
                        {% endfor %}
                    </div>
                    {{ form_rest(form) }}
                {{ form_end(form) }}
            </div>
        </div>
    </div>

{%- endblock content %}

{% block head_style %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/webfactoryform/css/lib/select2.min.css') }}">
{% endblock head_style %}

{% block foot_script %}
    {{ parent() }}
    <script src="{{ asset('bundles/webfactoryform/js/lib/select2.full.min.js') }}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/i18n/es.js"></script>

    <script>
        var collectionCount = '{{ form.players|length }}',
            playerList = $('#player-list')
        ;

        $(document).ready(function() {
            if (collectionCount == 0) {
                var newWidget = playerList.attr('data-prototype');
                newWidget = newWidget.replace(/__name__/g, collectionCount);
                playerList.append(newWidget);
                setAutocomplete($('#group_type_players_'+collectionCount+'_player'));

                collectionCount++;
            }

            playerList.on('click', '.collection-add', function(e) {
                e.preventDefault();

                var newWidget = playerList.attr('data-prototype');
                newWidget = newWidget.replace(/__name__/g, collectionCount);

                $(this).closest('.form-group').parent().append(newWidget);
                setAutocomplete($('#group_type_players_'+collectionCount+'_player'));

                collectionCount++;
            });

            playerList.on('click', '.collection-delete', function(e) {
                e.preventDefault();
                $(this).closest('.form-group').remove();
            });

            $.each($('select'), function() {
                setAutocomplete($(this));
            })
        });

        function setAutocomplete(widget) {
            widget.select2({
                language: "es",
                ajax: {
                    url: "{{ path('frontend_group_search_player') }}",
                    dataType: 'json',
                    delay: 500,
                    data: function (params) {
                        return {
                            q: params.term, // search term
                            page: params.page
                        };
                    },
                    processResults: function (data, params) {
                        params.page = params.page || 1;

                        return {
                            results: data,
                            pagination: {
                                more: (params.page * 30) < data.total_count
                            }
                        };
                    }
                },
                escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
                minimumInputLength: 3,
                templateResult: formatResponse, // omitted for brevity, see the source of this page
                templateSelection: function (response) {return response.fullName || response.text;}
            });
        }

        function formatResponse (response) {

            if (response.loading) return 'Cargango resultados';

            var markup = "<div class='select2-result-repository clearfix'>" +
                    "<div class='select2-result-repository__meta'>" +
                    "<div class='select2-result-repository__title'>" + response.fullName + "</div>";

            return markup;
        }
    </script>
{% endblock %}

src/AndresGotta/Bundle/GroupBundle/Resources/views/Frontend/Group/edit.html.twig
{% extends '@AndresGottaGroup/Frontend/Group/create.html.twig' %}

src/AndresGotta/Bundle/GroupBundle/Resources/views/Frontend/Group/index.html.twig
{% extends '::base.html.twig' %}

{% block content -%}

    <div class="nuevo-dashboard">
        <div class="reportarea">
            {% include '@AndresGottaHomepage/Frontend/Homepage/dashboard_sidebar.html.twig' %}

            <div class="bloque-central-stats">
                {% for groupPlayer in groups %}
                    {% set group = groupPlayer.group %}
                    {% if group.authorized %}
                        <a class="mega-box-a hvr-shutter-out-horizontal" href="#" title="{{ group.name }}">
                            {{ group.name }} <span>{{ 'more'|trans }}</span>
                        </a>
                        <div class="group-data" style="display:none">
                            {% if app.user in group.userAdmins %}
                                <a href="{{ path('frontend_group_edit', {id: group.id}) }}" class="btn btn-primary">{{ 'Edit group'|trans }}</a>
                            {% else %}
                                {% set playerGroup = app.user.playerByGroup(group) %}
                                <a href="{{ path('frontend_group_view_user', {group: group.id, player: playerGroup.id }) }}"
                                   class="btn btn-primary" title="Ver comparativas del jugador">
                                    {{ 'Result'|trans }}
                                </a>
                                {% if playerGroup.wannaBeAdmin == false %}
                                    <a href="{{ path('frontend_group_request_admin', { 'id': group.id }) }}"
                                       class="btn btn-primary" title="Solicitar ser administrador del grupo">
                                        {{ 'Admin'|trans }}
                                    </a>
                                {% endif %}
                            {% endif %}
                            <table class="table table-hover table-group" >
                                <thead>
                                <tr>
                                    <th>{{ 'Players'|trans }}</th>
                                    <th>{{ 'Confirmed'|trans }}</th>
                                    <th>{{ 'Status'|trans }}</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for user in group.players if not user.isAdmin %}
                                    <tr>
                                        <td>{{ user.player }}</td>
                                        <td>{% if user.isConfirmed == 0 %}{{ 'No'|trans }}{% else %}{{ 'Yes'|trans }}{% endif %}</td>
                                        <td>
                                            {% if user.groupMember %}
                                                <span class="label label-success">{{ 'Active'|trans }}</span>
                                            {% else %}
                                                <span class="label label-danger">{{ 'Inactive'|trans }}</span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% set removed = constant('\\AndresGotta\\Bundle\\GroupBundle\\ValueObject\\PlayerStatuses::REMOVED') %}
                                            {% if user.isConfirmed == 1 and app.user in group.userAdmins %}
                                                {% if user.status == removed %}
                                                    {% set confirmed = constant('\\AndresGotta\\Bundle\\GroupBundle\\ValueObject\\PlayerStatuses::CONFIRMED') %}
                                                    <a href="{{ path('frontend_user_group_change', {group: group.id, user: user.id, status: confirmed}) }}" title="Volver agregar jugador">
                                                        <span class="glyphicons user_add"><i></i></span>
                                                    </a>
                                                {% else %}
                                                    <a href="{{ path('frontend_group_view_user', {group: group.id, player: user.id}) }}" title="Ver comparativas del jugador">
                                                        <span class="glyphicons stats"><i></i></span>
                                                    </a>
                                                    <a href="{{ path('frontend_user_group_change', {group: group.id, user: user.id, status: removed}) }}" title="Quitar jugador">
                                                        <span class="glyphicons user_remove"><i class="remove"></i></span>
                                                    </a>
                                                {% endif %}
                                            {% else %}
                                                {% if user.player == app.user %}
                                                    {% if user.status != removed %}
                                                        <a href="{{ path('frontend_group_show', {id: group.id}) }}">Ver invitación</a>
                                                    {% else %}
                                                        <span>Dado de baja</span>
                                                    {% endif %}
                                                {% endif %}
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <a class="mega-box-a hvr-shutter-out-horizontal" style="background:#333" title="{{ 'authorization pending'|trans }}">
                            {{ group.name }} <span style="color:#fff">{{ 'authorization pending'|trans }}</span>
                        </a>
                    {% endif %}
                {% else %}
                    <p>{{ 'no data'|trans }}</p>
                {% endfor %}
            </div>
        </div>
    </div>

{%- endblock content %}

{% block foot_script %}
    {{ parent() }}

    <script>
        $(function() {
            $('.mega-box-a').on('click', function() {
                $('.group-data').hide();

                $(this).next().slideDown('slow');
            })
        })
    </script>
{% endblock %}

src/AndresGotta/Bundle/GroupBundle/Resources/views/Frontend/Group/show.html.twig
{% extends '::base.html.twig' %}

{% block content -%}

    <div class="nuevo-dashboard">
        <div class="reportarea">
            {% include '@AndresGottaHomepage/Frontend/Homepage/dashboard_sidebar.html.twig' %}

            <div class="bloque-central-stats">

                <div class="pageblockservice pageblockbg">

                    <p>El usuario <strong>{{ group.admin }}</strong> lo invito a participar de este grupo.</p>

                    {% if not group_user_confirmed(group, app.user) %}
                        <a href="{{ path('frontend_group_toggle', {id: group.id}) }}" class="btn">{{ 'Confirm participant'|trans }}</a>
                    {% else %}
                        <p style="font-style: italic; font-weight: bolder">Ya estás participando de este grupo</p>
                        <a href="{{ path('frontend_group_toggle', {id: group.id}) }}" class="btn btn-danger">{{ 'Unconfirm participant'|trans }}</a>
                    {% endif %}
                </div>


            </div>
        </div>
    </div>

{%- endblock content %}

{% block foot_script %}
    {{ parent() }}

{% endblock %}